project:
  type: website
  output-dir: docs

website:
  page-footer: "Copyright 2025, Felipe Antonio Dzul Manzanilla | Fabi√°n Correa-Morales"
  title: "Mapas de Dengue en R (2025)"
  navbar:
    logo: imagenes/logo_curso_2024.png
    tools:
      - icon: twitter
        href: https://twitter.com/FdzulM
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    left:
      - href: index.qmd
        text: Objetivos
      - href: about.qmd
        text: Detalles
      - href: temario.qmd
        text: Temario
      - href: labs.qmd
        text: Laboratorios
      - href: links.qmd
        text: Referencias
      - href: contacto.qmd
        text: Contacto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

